In [ ]:
#Problem - 1: Array Creation:
import numpy as np

# 1
array_1 = np.empty((2, 2))
print(array_1)
print(" ")

# 2
array_2 = np.ones((4,2))
print(array_2)
print(" ")

# 3
array_3 = np.full((3, 3), 8)
print(array_3)
print(" ")

# 4
array_4 = np.zeros_like(array_3)
print(array_4)
print(" ")

# 5
array_5 = np.ones_like(array_3)
print(array_5)
print(" ")

# 6
new_list = [1,2,3,4]
array_6 = np.array(new_list)
print(array_6)
print(" ")

[[4.98911643e-310 0.00000000e+000]
 [6.84933548e-310 6.84927445e-310]]
 
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
 
[[8 8 8]
 [8 8 8]
 [8 8 8]]
 
[[0 0 0]
 [0 0 0]
 [0 0 0]]
 
[[1 1 1]
 [1 1 1]
 [1 1 1]]
 
[1 2 3 4]
 


In [ ]:
# Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
import numpy as np

# 1
array_1 = np.arange(10,50)
print(array_1,"\n")

# 2
array_2 = np.arange(0, 9).reshape(3, 3)
print(array_2,"\n")

# 3
array_3 = np.eye(3,3)
print(array_3,"\n")

# 4
array_4 = np.random.rand(30)
mean = np.mean(array_4)
print("The mean of ", array_4," is", mean,"\n")

# 5
array_5 = np.random.rand(10,10)
min_value = np.min(array_5)
max_value = np.max(array_5)
print("The minimum value of ", array_5," is", min_value,"\n")
print("The maximum value of ", array_5," is", max_value,"\n")

# 6
array_6 = np.zeros(10)
array_6[4] = 1
print(array_6,"\n")

# 7
array_7 = [1, 2, 0, 0, 4, 0]
reverse_array = array_7[::-1]
print(reverse_array,"\n")

# 8
array_8 = np.zeros((5,5))
array_8[0, :] = 1
array_8[-1, :] = 1
array_8[:, 0] = 1
array_8[:, -1] = 1
print(array_8,"\n")

# 9
array_9 = np.zeros((8,8))
array_9[1::2, ::2] = 1
array_9[::2, 1::2] = 1
print(array_9,"\n")

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49] 

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

The mean of  [0.45585956 0.23284693 0.97840461 0.1653264  0.89447117 0.49350715
 0.75874522 0.21137217 0.59438087 0.60218769 0.2040446  0.87423032
 0.17801267 0.1400055  0.53053666 0.90494609 0.01030904 0.56310758
 0.99232281 0.27778234 0.2945336  0.1016648  0.2228733  0.3026562
 0.65510386 0.54792926 0.82930297 0.46631575 0.5762577  0.82490045]  is 0.4961312423649901 

The minimum value of  [[0.953636   0.56292112 0.48118304 0.06837315 0.80597138 0.70397549
  0.31876314 0.15229277 0.65153721 0.11002303]
 [0.50235228 0.67049193 0.43559573 0.42092853 0.35020479 0.34934669
  0.37154097 0.42085158 0.4471959  0.28014393]
 [0.21618244 0.89887502 0.45303939 0.67518927 0.8661367  0.62401308
  0.34053693 0.49225306 0.52748949 0.31875059]
 [0.40013877 0.58624483 0.69740963 0.49858693 0.46183496 0.2373132

In [ ]:
# Problem - 3: Array Operations:
import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

# 1
print("Addition of two arrays")
print(np.add(x, y))
print(np.add(v, w),"\n")

# 2
print("Subtraction of two arrays")
print(np.subtract(x, y))
print(np.subtract(v, w),"\n")

# 3
print("Multiplication of array with integer")
print(np.multiply(x, 5),"\n")

# 4
print("Square of each element")
print(np.square(x),"\n")

# 5
print("Dot product")
print("v.w = ",np.dot(v, w))
print("x.v = ",np.dot(x, v))
print("x.y = ",np.dot(x, y),"\n")

# 6
concat_xy = np.vstack((x, y))

v_reshaped = v.reshape(-1, 1)
w_reshaped = w.reshape(-1, 1)
concat_vw = np.concatenate((v_reshaped, w_reshaped), axis=1)

print("Concatenate x and y along rows:")
print(concat_xy)

print("\nConcatenate v and w along columns:")
print(concat_vw)

# 7
print(np.concatenate(x, v))

Addition of two arrays
[[ 6  8]
 [10 13]]
[20 22] 

Subtraction of two arrays
[[-4 -4]
 [-4 -3]]
[-2 -2] 

Multiplication of array with integer
[[ 5 10]
 [15 25]] 

Square of each element
[[ 1  4]
 [ 9 25]] 

Dot product
v.w =  219
x.v =  [29 77]
x.y =  [[19 22]
 [50 58]] 

Concatenate x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenate v and w along columns:
[[ 9 11]
 [10 12]]


TypeError: only integer scalar arrays can be converted to a scalar index

In this case, the issue is that the np.concatenate function expects a list (or tuple) of arrays as its first input, but instead, the code is passing individual arrays like x and v directly, which isn't the correct format. The function needs a sequence (like a list or tuple) of arrays to work properly.

In [ ]:
# Problem - 4: Matrix Operations:
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# A * A^(-1) = I
A_inv = np.linalg.inv(A)
lhs_1 = np.dot(A, A_inv)

print("A * A_inv = \n", lhs_1)
print("Identity = \n", np.eye(2))

# Verify if A * A_inv is the identity matrix
if np.array_equal(lhs_1, np.eye(2)):
    print("Therefore, A * A_inv = I (Proven)\n")
else:
    print("A * A_inv does not equal to I\n")

# AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)

print("AB = \n", AB)
print("BA = \n", BA)

# Verify if AB equals BA
if np.array_equal(AB, BA):
    print("AB equals BA (but this is not typical for matrix multiplication)")
else:
    print("Therefore, AB does not equal to BA (Proven)\n")

# (AB)^T = B^T A^T
AB_T = np.transpose(np.dot(A, B))

# Calculate B^T A^T
BT_AT = np.dot(np.transpose(B), np.transpose(A))

# Print the results
print("Transpose of AB (AB)^T:")
print(AB_T)

print("\nProduct of B^T and A^T (B^T A^T):")
print(BT_AT)

# Verify if (AB)^T equals B^T A^T
if np.array_equal(AB_T, BT_AT):
    print("Therefore, (AB)^T = B^T A^T \n")
else:
    print("(AB)^T does not equal B^T A^T\n")



A * A_inv = 
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Identity = 
 [[1. 0.]
 [0. 1.]]
A * A_inv does not equal to I

AB = 
 [[23 13]
 [51 29]]
BA = 
 [[36 44]
 [13 16]]
Therefore, AB does not equal to BA (Proven)

Transpose of AB (AB)^T:
[[23 51]
 [13 29]]

Product of B^T and A^T (B^T A^T):
[[23 51]
 [13 29]]
Therefore, (AB)^T = B^T A^T (Proven)

